-- Table: public.Main

-- DROP TABLE IF EXISTS public."Main";

CREATE TABLE IF NOT EXISTS public."Main"
(
    "CREATION_TIME" "text",
    "ID" "text",
    "IS_DRAFT" "text",
    "SCENARIO_ID" "text",
    "PLATFORM_ID" "text",
    "STAGE" "text",
    "CARD_GETTING_TYPE" "text",
    "CARD_GETTING_CITY" "text",
    "MNEMONICS" "text",
    "AB_TEST" "text",
    "SENDING_TO_FLECS_TIME" "text",
    "FLECS_APPLICATION_ID" "text",
    "FIRST_NAME" "text",
    "LAST_NAME" "text",
    "MIDDLE_NAME" "text",
    "SEX" "text",
    "BIRTH_YEAR" "text",
    "MOBILE_PHONE" "text",
    "EMAIL" "text",
    "CODE_WORD" "text",
    "CUS" "text",
    "STATE" "text",
    "REGISTRATION_REGION_CODE" "text",
    "SERIES" "text",
    "SRC_NUMBER" "text",
    "ISSUE_DATE" "text",
    "OFFICE" "text",
    "OFFICE_CODE" "text",
    "BIRTH_PLACE" "text",
    "NAME" "text",
    "PAYMENT_SYSTEM" "text",
    "IS_INSTANT_CARD" "text",
    "EMBOSSING_NAME" "text",
    "CHOSEN_CREDIT_LIMIT" "text",
    "INCOME" "text",
    "SERIES1" "text",
    "STAGINIT" "text",
    "CONV_SPASS" "text",
    "SRC_NUMBER1" "text",
    "CONV_NPASS" "text",
    "ISSUE_DATE1" "text",
    "CONV_ISSUE_DATE" "text",
    "OFFICE_CODE1" "text",
    "CONV_OFFICE_CODE" "text",
    "OFFICE_1" "text",
    "CONV_OFFICE" "text",
    "BIRTH_YEAR1" "text",
    "CONV_BIRTH_YEAR" "text",
    "BIRTH_PLACE1" "text",
    "CONV_BIRTH_PLACE" "text",
    "REGISTRATION_REGION_CODE1" "text",
    "CONV_REGISTRATION_REGION_CODE" "text",
    "INCOME1" "text",
    "CONV_INCOME" "text",
    "CHOSEN_CREDIT_LIMIT1" "text",
    "CONV_CHOSEN_CREDIT_LIMIT" "text",
    "CODE_WORD1" "text",
    "CONV_CODE_WORD" "text",
    "CARD_GETTING_CITY1" "text",
    "CONV_CARD_GETTING_CITY" "text",
    "CARD_GETTING_TYPE1" "text",
    "CONV_CARD_GETTING_TYPE" "text",
    "SENDING_TO_FLECS_TIME1" "text",
    "CONV_FULL" "text",
    "DCONV_SPASS" "text",
    "DCONV_NPASS" "text",
    "DCONV_ISSUE_DATE" "text",
    "DCONV_OFFICE_CODE" "text",
    "DCONV_OFFICE" "text",
    "DCONV_BIRTH_YEAR" "text",
    "DCONV_BIRTH_PLACE" "text",
    "DCONV_REGISTRATION_REGION_CODE" "text",
    "DCONV_INCOME" "text",
    "DCONV_CHOSEN_CREDIT_LIMIT" "text",
    "DCONV_CODE_WORD" "text",
    "DCONV_CARD_GETTING_CITY" "text",
    "DCONV_CARD_GETTING_TYPE" "text",
    "DCONV_FULL" "text"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Main"
    OWNER to postgres;